### ISSUE TITLE
Display Bug in Default Stroke Style and Initial Grip Strength

### ISSUE THREAD

**Issue by The1nstructor** [fapinstructor/fapinstructor#61]
Probably due to #59 The Categories *Default Stroke Style* and *Initial Grip Strength* are no longer displayed correctly after an edit.

**Comment by LenAnderson** [comment]
I doubt that the commit addresses the root of the problem (unless some browsers have buggy implementation). You should be able to convert anything to its string representation by calling `String`.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String

This is also not casting like done in so many other languages where you do `(type) someValue`. Instead `String` is a function: `String(someValue)`.

You can also check directly in the console that this should work:

    let cast=undefined;
    let val = "some text";
    (cast || String)(val)

Ok, checked out `handleChange` in the debugger and I think I found out what's going wrong. The config page does not use `<select>` for the dropdowns but some fancy JS implementation that already has its value as a Number. Since I wrongly expected for #59 that all inputs follow the standards defaulting to `String` seemed fine. So either we should make sure to always cast to the correct type, or just don't do anything if no casting function is provided (which would be your commit :) )

![Imgur](https://i.imgur.com/pwGYruE.png)

**Comment by The1nstructor** [comment]
Mhm what du you think is more suitable in terms of usability?

I think not to cast if it is not explicitly specified seems suitable 😄

**Comment by The1nstructor** [comment]
>  So either we should make sure to always cast to the correct type, or just don't do anything if no casting function is provided (which would be your commit :) )

I think we should do both.

**Comment by LenAnderson** [comment]
> better to only cast if explicitly wished by the function caller

agreed
